### ISSUE TITLE
Epic: `Invoice` refactoring to `Payment`, with invoice and receipt PDFs generated dynamically

### ISSUE THREAD

**Issue by cmutel** [sentier-dev/dds_registration#107]
- [x] Create workflow log of all current processes
- [x] Refactor some repeated logic in the model classes
- [x] Change `Invoice` to `Payment`
- [x] Add invoice generation to `Payment`
- [x] Add receipt generation to `Payment`
- [x] Fix PDF generation differences for membership
